name: sigrid-pullrequest
on:
  pull_request:
    branches:
      - "main"

jobs:
  sigridci:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Download Sigrid CI
        run: git clone https://github.com/Software-Improvement-Group/sigridci.git sigridci

      - name: Run Sigrid CI
        env:
          SIGRID_CI_TOKEN: ${{ secrets.CI_TOKEN }}
          # Or you can use CI_TOKEN_HILAS
          # SIGRID_CI_TOKEN: ${{ secrets.CI_TOKEN_HILAS }}
        run: |
          cd sigridci/sigridci
          python sigridci.py --customer hhsproject2 --system 2023-Projectgroep-H-1-SE-4d --source .
